### PR TITLE
add rps logo

### PR DESCRIPTION
**Pull request by bnfish**
@birdage this should be good to go, but let me know if not

cc: @kknee

### CODE REVIEW

**Comment by birdage** [comment]
@bnfish looks like you have a sync issue? try and rebase and fix the merge conflicts.

**Comment by bnfish** [comment]
apologies, @birdage; should be alright now.

**Comment by birdage** [comment]
@bnfish i think someone like @lukecampbell might need to deploy this.

**Comment by lukecampbell** [comment]
Redeployed

**Pull request merged**
